vivalviar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .core.views import home, history, special_participation, photos, playlist, contact_us, champions, \
    CircuitDetailView, CircuitListView, champions_team, BestYearPageView, get_player_stats

urlpatterns = []
if settings.DEVELOPER:
    urlpatterns += [
        path('admin/doc/', include('django.contrib.admindocs.urls')),
    ]

urlpatterns += [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('historia/', history, name='history'),
    path('campeoes/', champions, name='champions'),
    path('ajax/get_player_stats/', get_player_stats, name='get_player_stats'),
    path('campeoes/times/', champions_team, name='champions_team'),
    path('participacoes_especiais/', special_participation, name='special_participation'),
    path('melhores_do_ano/', BestYearPageView.as_view(), name='best_year'),
    path('fotos/', photos, name='photos'),
    path('videos/', playlist, name='playlist'),
    path('fale_conosco/', contact_us, name='contact_us'),
    path('circuitos/', CircuitListView.as_view(), name='circuit-list'),
    path('circuitos/<int:pk>/', CircuitDetailView.as_view(), name='circuit-detail')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

vivalviar/core/models.py
import itertools
from cloudinary.models import CloudinaryField
from django.db import models
from django.db.models import Sum, Case, When, Value, IntegerField, Count, Q, F, PositiveIntegerField, Avg
from django.utils.html import format_html
from django_countries.fields import CountryField

from vivalviar.core.managers import RankingQuerySet


class Banner(models.Model):
    title = models.CharField('título', max_length=250, unique=True)
    image = CloudinaryField('imagem', help_text='Imagem com: 873 X 1280 pixels')

    def image_thumbnail_300(self):
        return format_html(self.image.image(width=300, height=300, crop="thumb"))

    image_thumbnail_300.allow_tags = True
    image_thumbnail_300.short_description = 'imagem'

    def __str__(self):
        return self.title


class Sponsor(models.Model):
    name = models.CharField('nome', max_length=250, unique=True)
    link = models.CharField(max_length=250)
    logo = CloudinaryField('logotipo', help_text='Imagem com: 350 X 350 pixels')
    position = models.IntegerField('posição', default=0)

    def logo_thumbnail_350(self):
        return format_html(self.logo.image(width=350, height=350, crop="thumb"))

    logo_thumbnail_350.allow_tags = True
    logo_thumbnail_350.short_description = 'logotipo'

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'patrocinador'
        verbose_name_plural = 'patrocinadores'
        ordering = ('position', 'name')


class SpecialParticipation(models.Model):
    name = models.CharField('nome', max_length=250, unique=True)
    image = CloudinaryField('imagem', help_text='Imagem com: 300 X 300 pixels')
    country = models.CharField('país', max_length=255, null=True, blank=True)

    def image_crop_300(self):
        return format_html(self.image.image(width=300, height=300, crop="fill", gravity="face"))

    image_crop_300.allow_tags = True
    image_crop_300.short_description = 'imagem'

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'participação especial'
        verbose_name_plural = 'participações especiais'
        ordering = ('name',)


class Photo(models.Model):
    title = models.CharField('título', max_length=250, unique=True)
    image = CloudinaryField('imagem')

    def image_thumbnail_300(self):
        return format_html(self.image.image(width=300, height=300, crop="thumb"))

    image_thumbnail_300.allow_tags = True
    image_thumbnail_300.short_description = 'imagem'

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'foto'
        verbose_name_plural = 'fotos'
        ordering = ('title',)


class PlayList(models.Model):
    title = models.CharField('título', max_length=250, unique=True)
    code = models.CharField('código', max_length=60, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)


class Video(models.Model):
    title = models.CharField('título', max_length=250)
    code = models.CharField('código', max_length=60, unique=True)
    play_list = models.ForeignKey('PlayList', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Team(models.Model):
    name = models.CharField('nome', max_length=250, unique=True)
    logo = CloudinaryField('logotipo', null=True, blank=True, help_text='Imagem com: 350 X 350 pixels')

    def logo_fill_350(self):
        return format_html(self.logo.image(width=350, height=350, crop="fill"))

    logo_fill_350.allow_tags = True
    logo_fill_350.short_description = 'logotipo'

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'time'
        verbose_name_plural = 'times'
        ordering = ('name',)


class Player(models.Model):
    name = models.CharField('nome', max_length=250, unique=True)
    team = models.ForeignKey('Team', verbose_name=Team._meta.verbose_name, on_delete=models.SET_NULL, null=True,
                             blank=True)
    country = CountryField('país', default='BR')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'jogador'
        verbose_name_plural = 'jogadores'
        ordering = ('name',)


class Circuit(models.Model):
    description = models.CharField('descrição', max_length=250, unique=True)
    score_by_team = models.BooleanField('pontuação por time', default=False)

    @property
    def players_list(self):
        # qs = Ranking.objects.filter(tournament__in=self.tournament_set.all()) \
        #     .values('player__name', 'tournament') \
        #     .annotate(
        #     points=
        #     (
        #         (
        #             Count('tournament__ranking__id', output_field=IntegerField())
        #             - Avg('position', output_field=IntegerField())
        #             + 1
        #         ) * 10
        #     ) +
        #     Case(
        #         When(position=1, then=Value(15)),
        #         When(position=2, then=Value(5)),
        #         default=Value(0),
        #         output_field=IntegerField(),
        #     ),
        #
        # ).order_by('player__name')
        #
        # grouped = itertools.groupby(qs, lambda d: d.get('player__name'))
        #
        # players_list = [{'player__name': label,
        #                  'points': int(sum([x['points'] for x in value])),
        #                  }
        #                 for label, value in grouped]
        #
        # return players_list
        return Ranking.objects.filter(tournament__in=self.tournament_set.all()).score_players()

    @property
    def teams_list(self):
        # return Ranking.objects.filter(tournament__in=self.tournament_set.all()).exclude(player__team__isnull=True).score_teams()
        return Ranking.objects.filter(tournament__in=self.tournament_set.all()).score_teams()

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'circuito'
        verbose_name_plural = 'circuitos'
        ordering = ('description',)


class Tournament(models.Model):
    description = models.CharField('descrição', max_length=250, unique=True)
    circuit = models.ForeignKey('Circuit', on_delete=models.SET_NULL, verbose_name='circuito', null=True, blank=True)
    players = models.ManyToManyField('Player', through='Ranking')
    date = models.DateField('data', null=True, blank=True)
    PRESENTIAL = 'P'
    ONLINE = 'O'
    TYPE_CHOICES = (
        (ONLINE, 'Online'),
        (PRESENTIAL, 'Presencial'),
    )
    type = models.CharField(
        'tipo',
        max_length=1,
        choices=TYPE_CHOICES,
        default=ONLINE,
    )

    @property
    def players_count(self):
        return self.players.count()

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'torneio'
        verbose_name_plural = 'torneios'
        ordering = ('description',)


class Ranking(models.Model):
    player = models.ForeignKey('Player', on_delete=models.PROTECT)
    tournament = models.ForeignKey('Tournament', on_delete=models.PROTECT)
    position = models.PositiveIntegerField('posição')

    objects = RankingQuerySet().as_manager()

    def __str__(self):
        return str(self.player)

    class Meta:
        verbose_name = 'classificação'
        verbose_name_plural = 'classificações'
        ordering = ('tournament', 'position')
        unique_together = ('tournament', 'position')

vivalviar/core/views.py
import itertools

from django.http import JsonResponse
from django.views.generic import TemplateView, DetailView, ListView

from .models import Banner, Sponsor, SpecialParticipation, Photo, PlayList, Ranking, Circuit, Player


class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['banner_list'] = Banner.objects.all()
        context['sponsor_list'] = Sponsor.objects.all()
        return context


home = HomePageView.as_view()

history = TemplateView.as_view(
    template_name="history.html"
)


class SpecialParticipationPageView(TemplateView):
    template_name = "special_participation.html"

    def get_context_data(self, **kwargs):
        context = super(SpecialParticipationPageView, self).get_context_data(**kwargs)
        context['special_participation_list'] = SpecialParticipation.objects.all()
        return context


special_participation = SpecialParticipationPageView.as_view()


class PhotosPageView(TemplateView):
    template_name = "photos.html"

    def get_context_data(self, **kwargs):
        context = super(PhotosPageView, self).get_context_data(**kwargs)
        context['photo_list'] = Photo.objects.all()
        return context


photos = PhotosPageView.as_view()


class PlayListPageView(TemplateView):
    template_name = "videos.html"

    def get_context_data(self, **kwargs):
        context = super(PlayListPageView, self).get_context_data(**kwargs)
        context['playlist_list'] = PlayList.objects.all()
        return context


playlist = PlayListPageView.as_view()

contact_us = TemplateView.as_view(
    template_name="contact_us.html"
)


# TODO: Falta todos os campos necessários
def get_player_stats(request):
    player__pk = request.GET.get('pk', None)
    data = {
        'name': Player.objects.get(pk=player__pk).name,
        'tournament_count': Ranking.objects.filter(player__pk=player__pk).count()
    }
    return JsonResponse(data)


class ChampionsPageView(TemplateView):
    template_name = "champions_individual.html"

    def get_context_data(self, **kwargs):
        context = super(ChampionsPageView, self).get_context_data(**kwargs)
        # ranking_first_list = Ranking.objects.filter(position__lte=3)\
        #     .values('player__name', 'player__country') \
        #     .annotate(
        #         player_position_1st=Sum(
        #             Case(
        #                 When(position=1, then=Value(1)),
        #                 default=Value(0),
        #                 output_field=IntegerField(),
        #             )
        #         ),
        #         player_position_2nd=Sum(
        #             Case(
        #                 When(position=2, then=Value(1)),
        #                 default=Value(0),
        #                 output_field=IntegerField(),
        #             )
        #         ),
        #         player_position_3rd=Sum(
        #             Case(
        #                 When(position=3, then=Value(1)),
        #                 default=Value(0),
        #                 output_field=IntegerField(),
        #             )
        #         ),
        #         player_position_total=Sum(
        #             Case(
        #                 When(position__lte=3, then=Value(1)),
        #                 default=Value(0),
        #                 output_field=IntegerField(),
        #             )
        #         ),
        #     ) \
        #     .order_by('-player_position_1st', '-player_position_2nd', '-player_position_3rd', 'player__name')
        ranking_list = Ranking.objects.champions_individual()
        context['ranking_list'] = ranking_list
        return context


champions = ChampionsPageView.as_view()


class ChampionsTeamPageView(TemplateView):
    template_name = "champions_team.html"

    def get_context_data(self, **kwargs):
        context = super(ChampionsTeamPageView, self).get_context_data(**kwargs)
        ranking_list = Ranking.objects.champions_team()
        context['ranking_list'] = ranking_list
        return context


champions_team = ChampionsTeamPageView.as_view()


class CircuitDetailView(DetailView):
    model = Circuit


class CircuitListView(ListView):
    model = Circuit


class BestYearPageView(TemplateView):
    template_name = "best_year.html"

    def get_context_data(self, **kwargs):
        context = super(BestYearPageView, self).get_context_data(**kwargs)
        ranking_list = []
        for circuit in Circuit.objects.all():
            ranking_list += circuit.players_list

        ranking_list = sorted(ranking_list, key=lambda k: k['player__name'])

        grouped = itertools.groupby(ranking_list, lambda d: d.get('player__name'))
        ranking_list = [{'player__name': label,
                         'points': int(sum([x['points'] for x in value])),
                         }
                        for label, value in grouped]

        context['ranking_list'] = ranking_list
        return context

vivalviar/core/templates/best_year.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block head %}
    <title>Melhores do Ano | Vivalviar Poker</title>
    <meta name="description" content="Página dedicada aos melhores do ano da Vivalviar Poker.">
    <meta name="keywords" content="poker, pokerstars, poker star, poker senhas, poker online, poker regras, poker gratis,
    como jogar poker, jogar poker, torneios de poker, quem joga poker, jogadores de poker, vivalviar, vivalviarpoker,
    poker amador, poker profissional, melhores do poker, melhores do ano, melhor jogador do ano,
    melhores jogadores de poker, melhor do poker">
{% endblock %}

{% block og %}
    <meta property="og:title" content="Melhores do Ano" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="{% static "assets/img/logo.png" %}" />
    <meta property="og:description" content="Página dedicada aos melhores do ano da Vivalviar Poker." />
    <meta property="og:site_name" content="Vivalviar Poker" />
{% endblock og %}

{% block twitter %}
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@VivalviarPoker">
    <meta name="twitter:title" content="Melhores do Ano">
    <meta name="twitter:description" content="Página dedicada aos melhores do ano da Vivalviar Poker.">
    <meta name="twitter:creator" content="@VivalviarPoker">
    <meta name="twitter:image" content="{% static "assets/img/logo.png" %}">
    <meta name="twitter:domain" content="www.vivalviar.com.br">
{% endblock twitter %}

{% block content %}
    <div class="section" id="historico">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <h2>Melhores do Ano</h2>
                    <table class="table table-hover table-striped rank">
                        <thead>
                            <th class="text-right">#</th>
                            <th>Nome</th>
                            <th class="text-right table-active">Pontos</th>
                        </thead>
                        <tbody>
                        {% for champions in ranking_list|dictsortreversed:'points' %}
                            <tr>
                                <td class="text-right"></td>
                                <td>{{ champions.player__name }}</td>
                                <td class="text-right table-active">{{ champions.points }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

vivalviar/core/templates/champions.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load countries %}
{% load cloudinary %}

{% block head %}
    <link rel="stylesheet" href="{% static 'flags/sprite.css' %}">

    <title>Campeões | Vivalviar Poker</title>
    <meta name="description" content="Ranking de todos os nossos campeões do Vivalviar Poker.">
    <meta name="keywords" content="poker, pokerstars, poker star, poker senhas, poker online, poker regras, poker gratis,
    como jogar poker, jogar poker, torneios de poker, quem joga poker, jogadores de poker, campeoes de poker,
    campeonato de poker, campeonatos de poker">
{% endblock head %}

{% block og %}
    <meta property="og:title" content="Campeões"/>
    <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
    <meta property="og:image" content="{% static "assets/img/logo.png" %}"/>
    <meta property="og:description" content="Ranking de todos os nossos campeões do Vivalviar Poker."/>
    <meta property="og:site_name" content="Vivalviar Poker"/>
{% endblock og %}

{% block twitter %}
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@VivalviarPoker">
    <meta name="twitter:title" content="Campeões">
    <meta name="twitter:description" content="Ranking de todos os nossos campeões do Vivalviar Poker.">
    <meta name="twitter:creator" content="@VivalviarPoker">
    <meta name="twitter:image" content="{% static "assets/img/logo.png" %}">
    <meta name="twitter:domain" content="www.vivalviar.com.br">
{% endblock twitter %}

{% block content %}
    <div class="section" id="historico">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <h2>{% block champions_title %}{% endblock %}</h2>
                    <table class="table table-hover table-striped rank">
                        <thead>
                        <th class="text-right">#</th>
                        {% block champions_ths %}{% endblock %}
                        <th class="text-right table-warning img-raised">
                            1º
                            <img src="{% static "assets/img/medal/medal-1st_160_good.png" %}" class="img-responsive"
                                 style="max-height: 1rem">
                        </th>
                        <th class="text-right">
                            2º
                            <img src="{% static "assets/img/medal/medal-2nd_160_good.png" %}" class="img-responsive"
                                 style="max-height: 1rem">
                        </th>
                        <th class="text-right">
                            3º
                            <img src="{% static "assets/img/medal/medal-3rd_160_good.png" %}" class="img-responsive"
                                 style="max-height: 1rem">
                        </th>
                        <th class="text-right">
                            Total
                            <img src="{% static "assets/img/medal/medals-total_160_good.png" %}" class="img-responsive"
                                 style="max-height: 1rem">
                        </th>
                        </thead>
                        <tbody>
                        {% for champions in ranking_list %}
                            {% get_country champions.player__country as country %}
                            <tr>
                                <td class="text-right"></td>
                                {% block champions_tds %}{% endblock %}
                                <td class="text-right table-warning img-raised">{{ champions.player_position_1st }}</td>
                                <td class="text-right">{{ champions.player_position_2nd }}</td>
                                <td class="text-right">{{ champions.player_position_3rd }}</td>
                                <td class="text-right">{{ champions.player_position_total }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{#    TODO: Mexer daqui pra baixo!!!#}
    <!-- Modal -->
    <div class="modal fade" id="statsPlayerModal" tabindex="-1" role="dialog" aria-labelledby="statsPlayerModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="statsPlayerModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Nome: <span id="statsPlayerModal_name"></span><br>
                    Torneios: <span id="statsPlayerModal_tournament_count"></span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <script type="application/javascript">
        function showStats(jogador_id) {
            $.ajax({
                url: '/ajax/get_player_stats/',
                data: {
                    'pk': jogador_id
                },
                dataType: 'json',
                success: function (data) {
                    $("#statsPlayerModal_name").text(data.name);
                    $("#statsPlayerModal_tournament_count").text(data.tournament_count);
                    $('#statsPlayerModal').modal();
                }
            });
        };
    </script>

{% endblock content %}

vivalviar/core/templates/champions_individual.html
{% extends 'champions.html' %}

{% block champions_title %}
    Campeões Vivalviar Poker:
{% endblock %}

{% block champions_ths %}
    <th>Nacionalidade</th>
    <th>Nome</th>
{% endblock %}

{% block champions_tds %}
    <td><i class="{{ country.flag_css }}"></i> {{ country.name }}</td>
    <td><a href="javascript:void(0)" onclick="showStats({{ champions.player__pk }});">{{ champions.player__name }}</a></td>
{% endblock %}

vivalviar/core/templates/champions_team.html
{% extends 'champions.html' %}
{% load cloudinary %}

{% block champions_title %}
    Times Campeões:
{% endblock champions_title %}

{% block champions_ths %}
    <th></th>
    <th>Time</th>
{% endblock %}

{% block champions_tds %}
    <td>
        {% if champions.player__team__logo %}
            {% cloudinary champions.player__team__logo height=100 crop="fill" alt=champions.player__team__name class='img-responsive' style='height: 2rem;' %}
        {% endif %}
    </td>
    <td>{{ champions.player__team__name }}</td>
{% endblock %}

vivalviar/core/templates/contact_us.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block head %}
    <title>Fale Conosco | Vivalviar Poker</title>
    <meta name="description" content="Tem alguma dúvida ou sugestão? Entre em contato, teremos o maior prazer em atendê-lo.">
    <meta name="keywords" content="poker, pokerstars, poker star, poker senhas, poker online, poker regras, poker gratis,
    como jogar poker, jogar poker, torneios de poker, quem joga poker, jogadores de poker, contato do poker,
    contato vivalviar, suporte vivalviar, vivalviar é confiavel?,  vivalviar, vivalviarpoker, poker amador, poker profissional">
{% endblock %}

{% block og %}
    <meta property="og:title" content="Fale Conosco" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="{% static "assets/img/logo.png" %}" />
    <meta property="og:description" content="Tem alguma dúvida ou sugestão? Entre em contato, teremos o maior prazer em atendê-lo." />
    <meta property="og:site_name" content="Vivalviar Poker" />
{% endblock og %}

{% block twitter %}
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@VivalviarPoker">
    <meta name="twitter:title" content="Fale Conosco">
    <meta name="twitter:description" content="Tem alguma dúvida ou sugestão? Entre em contato, teremos o maior prazer em atendê-lo.">
    <meta name="twitter:creator" content="@VivalviarPoker">
    <meta name="twitter:image" content="{% static "assets/img/logo.png" %}">
    <meta name="twitter:domain" content="www.vivalviar.com.br">
{% endblock twitter %}

{% block content %}
    <div class="section" id="fale_conosco">
        <div class="contact-content">
            <div class="container">
                <h2 class="title">Entre em contato!</h2>
                <div class="row">
                    <div class="col-md-12">
                        <p class="description">Podemos ajudá-lo em algo?
                            <br>
                            <br>
                        </p>
                        E-mail: <a
                            href="mailto:vivalviarpoker.contato@gmail.com">vivalviarpoker.contato@gmail.com</a><br>
                        WhatsApp: <a href="https://api.whatsapp.com/send?phone=5527998542169">+55 27 99854-2169</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

vivalviar/core/templates/videos.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block head %}
    <title>Vídeos | Vivalviar Poker</title>
    <meta name="description" content="Vídeos que contam nossa história no cenário do Poker Brasileiro.">
    <meta name="keywords" content="poker, pokerstars, poker star, poker senhas, poker online, poker regras, poker gratis,
    como jogar poker, jogar poker, torneios de poker, quem joga poker, jogadores de poker, vídeos de poker, vivalviar,
    vivalviarpoker, poker amador, poker profissional">
{% endblock %}

{% block og %}
    <meta property="og:title" content="Vídeos" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:image" content="{% static "assets/img/logo.png" %}" />
    <meta property="og:description" content="Vídeos que contam nossa história no cenário do Poker Brasileiro." />
    <meta property="og:site_name" content="Vivalviar Poker" />
{% endblock og %}

{% block twitter %}
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@VivalviarPoker">
    <meta name="twitter:title" content="Vídeos">
    <meta name="twitter:description" content="Vídeos que contam nossa história no cenário do Poker Brasileiro.">
    <meta name="twitter:creator" content="@VivalviarPoker">
    <meta name="twitter:image" content="{% static "assets/img/logo.png" %}">
    <meta name="twitter:domain" content="www.vivalviar.com.br">
{% endblock twitter %}

{% block content %}
<div class="section section-videos text-center" id="videos">
    <div class="container">
        <h2 class="title">Vídeos</h2>

        {% for playlist in playlist_list %}
            <h3>{{ playlist.title }}</h3>
            <div class="row collections">
                {% if playlist.code %}
                    <div class="col-md-12">
                        <div class="video-container">
                            <iframe type="text/html" width="560" height="315"
                                    src="https://www.youtube.com/embed/?listType=playlist&list={{ playlist.code }}&rel=0"
                                    frameborder="0" allowfullscreen></iframe>
                        </div>
                    </div>
                {% endif %}
                {% for video in playlist.video_set.all %}
                    <div class="col-md-6">
                        <span class="title">{{ video.title }}</span>
                        <div class="video-container">
                            <iframe type="text/html" width="560" height="315"
                                    src="https://www.youtube.com/embed/{{ video.code }}?rel=0"
                                    frameborder="0" allowfullscreen></iframe>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if not forloop.last %}
                <hr/>
                <br>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock content %}